#!/bin/bash

export JAVA_HOME=/usr/lib/jvm/java-23-openjdk
export PATH_TO_FX="/usr/lib/jvm/javafx-sdk-23/lib"
export PATH="$JAVA_HOME/bin:$PATH"

jar_path="$HOME/.local/bin/JetUML/JetUML-3.8.jar"

java --module-path "$PATH_TO_FX" --add-modules=javafx.controls,javafx.swing,java.desktop,java.prefs -jar "$jar_path"
