#!/bin/bash

JAVA_DIR="$HOME/.local/java"
SYSTEM_JAVA_DIR="/usr/lib/jvm"

export JAVA_HOME="$JAVA_DIR/java-23-openjdk"
export PATH_TO_FX="$JAVA_DIR/javafx-sdk-23/lib"
export PATH="$JAVA_HOME/bin:$PATH"

jar_path="$JAVA_DIR/JetUML-3.8.jar"

java --module-path "$PATH_TO_FX" --add-modules=javafx.controls,javafx.swing,java.desktop,java.prefs -jar "$jar_path"
