#!/bin/bash

USER_JAVA_DIR="$HOME/.local/java"
SYSTEM_JAVA_DIR="/usr/lib/jvm"

# keep one of them
# JAVA_DIR=$SYSTEM_JAVA_DIR
JAVA_DIR=$USER_JAVA_DIR

sys_ver=$("$SYSTEM_JAVA_DIR/java-23-openjdk/bin/java" -version 2>&1)
usr_ver=$("$USER_JAVA_DIR/java-23-openjdk/bin/java" -version 2>&1)
cur_ver=$(java --version 2>&1)
# Print Java versions for debugging
echo -e "\n🔍 Java Version Check:"
echo -e "  🖥  System Java: \n$sys_ver\n"
echo -e "  🏠  User Java:   \n$usr_ver\n"
echo -e "  🚀   Current Java:   \n$cur_ver\n"

export JAVA_HOME="$JAVA_DIR/java-23-openjdk"
export PATH_TO_FX="$JAVA_DIR/javafx-sdk-23/lib"
export PATH="$JAVA_HOME/bin:$PATH"

jar_path="$USER_JAVA_DIR/JetUML-3.8.jar"

java --module-path "$PATH_TO_FX" --add-modules=javafx.controls,javafx.swing,java.desktop,java.prefs -jar "$jar_path"
